- name: mysql config
  hosts: mysql
  become: yes
  vars:
    mysql_root_pass: ExpenseApp@1
    login_host: mysql.hraje.online
  tasks:
  - name: ansible to install PyMySQL
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9    


  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: start the mysql-server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect mysql mysql-server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_pass }}"
      login_host: "{{ login_host }}"
    ignore_errors: true
    register: mysql_info

  - name: print mysql info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: setup mysql root login_password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_pass }}"
    when: mysql_info.failed is true
